### ISSUE TITLE
Regex failing with PECO

### ISSUE THREAD

**Issue by Garulf** [tronikos/opower-hacs#11]
```
Traceback (most recent call last):
  File "/Volumes/homeassistant/.venv/lib/python3.10/site-packages/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
  File "/Volumes/HomeAssistant/custom_components/opower/coordinator.py", line 67, in _async_update_data
    await self.api.async_login()
  File "/Volumes/homeassistant/.venv/lib/python3.10/site-packages/opower/opower.py", line 151, in async_login
    self.access_token = await self.utility.async_login(
  File "/Volumes/homeassistant/.venv/lib/python3.10/site-packages/opower/utilities/exelon.py", line 44, in async_login
    settings = json.loads(re.search(r"var SETTINGS = ({.*});", result).group(1))
```

**Comment by Garulf** [comment]
I installed the `opower` package and ran similar code to debug and it works.

Not sure why it's having an issue with this bit of code.

```
(.venv) PS E:\Users\Garulf\opower_test> python .\main.py
E:\Users\Garulf\opower_test\main.py:10: DeprecationWarning: The object should be created within an async function
  session = aiohttp.ClientSession()
{'remoteResource': 'https://xzeepb2clookuppsta001.blob.core.windows.net/peco/aadb2ccustomui/unified.html', 'retryLimit': 3, 'trimSpacesInPassword': True, 'api': 'CombinedSigninAndSignup', 'csrf': 'd2tWRlNzRUs3MmVRMlVxcE1Oa2owMlk1bjBTVnBQWHBDMjhveXhvL2ZBbFl2dEJmZE50Mk9HYlA3R3hVemR1eUZEcG5aMTRJT0x3MVJTMWhOTGFCRXc9PTsyMDIzLTA4LTAyVDIxOjA3OjUwLjgzMTk5MzRaO01JajYvSU1RZ3lteUpHS0x5SGtyN1E9PTt7Ik9yY2hlc3RyYXRpb25TdGVwIjoxfQ==', 'transId': 'StateProperties=eyJUSUQiOiI1NGI3MjE0NC1iNTJiLTRlZDctOGQwOC1mNTg5ZGI3OTM3OTMifQ', 'pageViewId': 'a9bb06fd-074d-4f82-9377-6ee2283e8970', 'suppressElementCss': False, 'isPageViewIdSentWithHeader': False, 'allowAutoFocusOnPasswordField': True, 'pageMode': 1, 'config': {'showSignupLink': 'false', 'sendHintOnSignup': 'False', 'includePasswordRequirements': 'true', 'enableRememberMe': 'false', 'forgotPasswordLinkOverride': 'ForgotPasswordExchange', 'forgotPasswordLinkLocation': 'AfterInput', 'operatingMode': 'Email', 'announceVerCompleteMsg': 'True'}, 'hosts': {'tenant': '/euazurepeco.onmicrosoft.com/B2C_1A_SignIn', 'policy': 'B2C_1A_SignIn', 'static': 'https://secure1.peco.com/static/'}, 'locale': {'lang': 'en'}, 'xhrSettings': {'retryEnabled': True, 'retryMaxAttempts': 3, 'retryDelay': 200, 'retryExponent': 2, 'retryOn': ['error', 'timeout']}}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021D648A8BB0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000021D673AECE0>, 153954.125)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000021D6738CD30>
```

**Comment by Garulf** [comment]
I manually edited the `opower` package the integration is using to log the page its getting when trying to login.

This is what it loads:
```
<!doctype html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta charset="utf-8">

  <title>Accounts</title>
  <base href="/accounts/">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  
<link rel="stylesheet" href="/accounts/styles.6d67bd2c5a96a87deee8.css"></head>
<body>

  <app-root></app-root>
  <app-redirect></app-redirect>
<script src="/accounts/runtime-es2015.7d74949e1062d3e292a5.js" type="module"></script><script src="/accounts/runtime-es5.7d74949e1062d3e292a5.js" nomodule defer></script><script src="/accounts/polyfills-es5.bd1b4941665e9ce02e3c.js" nomodule defer></script><script src="/accounts/polyfills-es2015.f683d9b05c0834362594.js" type="module"></script><script src="/accounts/main-es2015.32bde0e5bffc28d6ef06.js" type="module"></script><script src="/accounts/main-es5.32bde0e5bffc28d6ef06.js" nomodule defer></script></body>
</html>
```

**Comment by tronikos** [comment]
Thanks for going the extra mile and including the response! That hinted me that the session was already signed in. I fixed the underlying library and I have https://github.com/home-assistant/core/pull/97752 to fix the official integration. I guess I can update this custom integration one last time before I archive it.

**Comment by tronikos** [comment]
Fixed in the latest release which as I said will likely be the last update of this custom integration.

**Comment by Garulf** [comment]
> Thanks for going the extra mile and including the response! 

No problem, thanks for taking the time to create this integration!

>That hinted me that the session was already signed in. I fixed the underlying library and I have [home-assistant/core#97752](https://github.com/home-assistant/core/pull/97752) to fix the official integration. I guess I can update this custom integration one last time before I archive it.

So that's what's going on?
I couldn't figure out why my test script and the integration would be receiving completely different pages in the same virtual env. 
I never thought of the session already being logged in.

>Fixed in the latest release which as I said will likely be the last update of this custom integration.

Thanks again!

**Comment by Garulf** [comment]
I upgraded the custom integration and I no longer receive any exceptions regarding regex.

I am however getting 403 errors. Since support for this custom integration has stopped where is the best place for issues on this?

**Comment by tronikos** [comment]
Best place to report issues is at https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+opower%22

If it's an issue of the underlying library then  https://github.com/tronikos/opower/issues

In your particular case the best place seems to be your utility.
