### ISSUE TITLE
KeyError: costToDate

### ISSUE THREAD

**Issue by Asherlc** [tronikos/opower-hacs#3]
See below for an error I'm getting, looks like whatever response PGE is sending isn't including some expected fields?

```
This error originated from a custom integration.

Logger: custom_components.opower.coordinator
Source: custom_components/opower/coordinator.py:67
Integration: Opower (documentation, issues)
First occurred: 5:01:21 PM (7 occurrences)
Last logged: 5:05:51 PM

Unexpected error fetching Opower data: 'costToDate'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/opower/coordinator.py", line 67, in _async_update_data
    forecasts = await self.api.async_get_forecast()
  File "/usr/local/lib/python3.10/site-packages/opower/opower.py", line 223, in async_get_forecast
    cost_to_date=float(forecast["costToDate"]),
KeyError: 'costToDate'
```

**Comment by ampersandru** [comment]
another user [mentioned this error](https://github.com/tronikos/opower-hacs/issues/2#issuecomment-1544918944) and he stated it fixed itself and started working after a few minutes. Has yours started working?

**Comment by Asherlc** [comment]
Mine has been going for a few hours or so and no luck unfortunately

**Comment by tronikos** [comment]
Please update to v0.0.4. Reopen if it didn't fix your issue.
