### ISSUE TITLE
Unexpected error fetching Opower data: 'opower:pge_elec_XXXXXXXXXX_energy_cost'

### ISSUE THREAD

**Issue by ampersandru** [tronikos/opower-hacs#7]
On HA 2023.6.3 and this error starting popping up:

```
This error originated from a custom integration.

Logger: custom_components.opower.coordinator
Source: custom_components/opower/coordinator.py:116
Integration: Opower (documentation, issues)
First occurred: June 25, 2023 at 11:41:25 PM (261 occurrences)
Last logged: 1:50:01 PM

Unexpected error fetching Opower data: 'opower:pge_elec_XXXXXXXXXX_energy_cost'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opower/coordinator.py", line 72, in _async_update_data
    await self._insert_statistics([forecast.account for forecast in forecasts])
  File "/config/custom_components/opower/coordinator.py", line 116, in _insert_statistics
    cost_sum = cast(float, stats[cost_statistic_id][0]["sum"])
                           ~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'opower:pge_elec_XXXXXXXXXX_energy_cost'
```

**Comment by nijhawank** [comment]
It is not just 2023.6.3 error, it also stopped working on my 2023.4.x instance

**Comment by tronikos** [comment]
Can you try updating to the latest 0.0.12 and let me know?

**Comment by nijhawank** [comment]
It seems to be working now. Thank you.
